// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwwJO3kvBVqIaiz99wm3jAh7S0bQ1UaJg',
    appId: '1:259159564635:web:88939b5760fb7f592c3a7e',
    messagingSenderId: '259159564635',
    projectId: 'expense-tracker-c9a91',
    authDomain: 'expense-tracker-c9a91.firebaseapp.com',
    storageBucket: 'expense-tracker-c9a91.firebasestorage.app',
    measurementId: 'G-QF893WM65Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtwBdUFEKHyk4xTJt3BR_Ji1GqMrxVUQg',
    appId: '1:259159564635:android:1dadf197584977092c3a7e',
    messagingSenderId: '259159564635',
    projectId: 'expense-tracker-c9a91',
    storageBucket: 'expense-tracker-c9a91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_IUUnjKqeLIQh_xdjLpSyQzl_s-tXkU4',
    appId: '1:259159564635:ios:d66692e999d0cbae2c3a7e',
    messagingSenderId: '259159564635',
    projectId: 'expense-tracker-c9a91',
    storageBucket: 'expense-tracker-c9a91.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_IUUnjKqeLIQh_xdjLpSyQzl_s-tXkU4',
    appId: '1:259159564635:ios:d66692e999d0cbae2c3a7e',
    messagingSenderId: '259159564635',
    projectId: 'expense-tracker-c9a91',
    storageBucket: 'expense-tracker-c9a91.firebasestorage.app',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwwJO3kvBVqIaiz99wm3jAh7S0bQ1UaJg',
    appId: '1:259159564635:web:0133c723ebfe0fdf2c3a7e',
    messagingSenderId: '259159564635',
    projectId: 'expense-tracker-c9a91',
    authDomain: 'expense-tracker-c9a91.firebaseapp.com',
    storageBucket: 'expense-tracker-c9a91.firebasestorage.app',
    measurementId: 'G-QBJ55172RL',
  );
}